name: missing_flash_drive
description: "The Missing Flash Drive - A Choose Your Own Adventure App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  audioplayers: ^6.0.0
  google_fonts: ^6.2.1
  video_player: ^2.8.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/scene_0.png
    - assets/images/scene_1.png
    - assets/images/scene_2.png
    - assets/images/scene_3.png
    - assets/images/scene_4.png
    - assets/images/scene_5.png
    - assets/images/scene_6.png
    - assets/images/scene_7.png
    - assets/images/scene_8.png
    - assets/images/splash_bg.png
    - assets/audio/bg_music.mp3
    - assets/audio/good_ending.mp3
    - assets/audio/bad_ending.mp3
